-libraryjars /opt/WTK2.5.2/lib/jsr184.jar:/opt/WTK2.5.2/lib/midpapi20.jar:/opt/WTK2.5.2/lib/cldcapi11.jar
-injars /home/volcan/j2mewtk/2.5.2/apps/TGame2/bin/TGame2.jar
-outjar /tmp/TGame2.jar
-keep public class * extends javax.microedition.midlet.MIDlet 
