-libraryjars D:\WTK23\lib\wma11.jar;D:\WTK23\lib\mmapi.jar;D:\WTK23\lib\jsr184.jar;D:\WTK23\lib\midpapi20.jar;D:\WTK23\lib\cldcapi11.jar
-injars D:\WTK23\apps\TGame2\bin\TGame2.jar
-outjar C:\DOCUME~1\Osama\LOCALS~1\Temp\TGame2.jar
-keep public class * extends javax.microedition.midlet.MIDlet 
